# Generated by Django 3.0.8 on 2020-07-20 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='skip',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='record',
            name='fullNameConfidenceScore',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='column',
            name='dataType',
            field=models.CharField(choices=[('firstname', 'firstname'), ('middlename', 'middlename'), ('accountnumber', 'accountnumber'), ('lastname', 'lastname'), ('dob', 'dob'), ('sex', 'sex'), ('street', 'street'), ('city', 'city'), ('state', 'state'), ('zip', 'zip')], max_length=40),
        ),
    ]
